version: '3.8'

services:
  portfolio-app:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./logs:/app/logs
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=portfolio123
    networks:
      - portfolio-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - portfolio-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - portfolio-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    networks:
      - portfolio-network

volumes:
  postgres_data:
  grafana_data:

networks:
  portfolio-network:
    driver: bridge
